version: '3.7'

services:
  web: 
    build: .
    container_name: web
    restart: always
    volumes:
      - .:/app
    environment: 
      - FLASK_ENV=development
      - API_KEY=1
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "80:80"
